
import { FontConfig, FontCategory } from '../types';

export const FONT_LIST: FontConfig[] = [
    // --- MODERN / SANS (40) ---
    { id: 'inter', name: 'Inter', family: '"Inter", sans-serif', category: 'Modern' },
    { id: 'roboto', name: 'Roboto', family: '"Roboto", sans-serif', category: 'Modern' },
    { id: 'poppins', name: 'Poppins', family: '"Poppins", sans-serif', category: 'Modern' },
    { id: 'montserrat', name: 'Montserrat', family: '"Montserrat", sans-serif', category: 'Modern' },
    { id: 'raleway', name: 'Raleway', family: '"Raleway", sans-serif', category: 'Modern' },
    { id: 'exo2', name: 'Exo 2', family: '"Exo 2", sans-serif', category: 'Modern' },
    { id: 'ubuntu', name: 'Ubuntu', family: '"Ubuntu", sans-serif', category: 'Modern' },
    { id: 'comfortaa', name: 'Comfortaa', family: '"Comfortaa", sans-serif', category: 'Modern' },
    { id: 'opensans', name: 'Open Sans', family: '"Open Sans", sans-serif', category: 'Modern' },
    { id: 'lato', name: 'Lato', family: '"Lato", sans-serif', category: 'Modern' },
    { id: 'notosans', name: 'Noto Sans', family: '"Noto Sans", sans-serif', category: 'Modern' },
    { id: 'nunito', name: 'Nunito', family: '"Nunito", sans-serif', category: 'Modern' },
    { id: 'rubik', name: 'Rubik', family: '"Rubik", sans-serif', category: 'Modern' },
    { id: 'quicksand', name: 'Quicksand', family: '"Quicksand", sans-serif', category: 'Modern' },
    { id: 'worksans', name: 'Work Sans', family: '"Work Sans", sans-serif', category: 'Modern' },
    { id: 'firasans', name: 'Fira Sans', family: '"Fira Sans", sans-serif', category: 'Modern' },
    { id: 'kanit', name: 'Kanit', family: '"Kanit", sans-serif', category: 'Modern' },
    { id: 'barlow', name: 'Barlow', family: '"Barlow", sans-serif', category: 'Modern' },
    { id: 'mukta', name: 'Mukta', family: '"Mukta", sans-serif', category: 'Modern' },
    { id: 'heebo', name: 'Heebo', family: '"Heebo", sans-serif', category: 'Modern' },
    { id: 'ibmplexsans', name: 'IBM Plex Sans', family: '"IBM Plex Sans", sans-serif', category: 'Modern' },
    { id: 'dmsans', name: 'DM Sans', family: '"DM Sans", sans-serif', category: 'Modern' },
    { id: 'ptsans', name: 'PT Sans', family: '"PT Sans", sans-serif', category: 'Modern' },
    { id: 'titillium', name: 'Titillium Web', family: '"Titillium Web", sans-serif', category: 'Modern' },
    { id: 'assistant', name: 'Assistant', family: '"Assistant", sans-serif', category: 'Modern' },
    { id: 'hind', name: 'Hind', family: '"Hind", sans-serif', category: 'Modern' },
    { id: 'arimo', name: 'Arimo', family: '"Arimo", sans-serif', category: 'Modern' },
    { id: 'cabin', name: 'Cabin', family: '"Cabin", sans-serif', category: 'Modern' },
    { id: 'josefinsans', name: 'Josefin Sans', family: '"Josefin Sans", sans-serif', category: 'Modern' },
    { id: 'dosis', name: 'Dosis', family: '"Dosis", sans-serif', category: 'Modern' },
    { id: 'mulish', name: 'Mulish', family: '"Mulish", sans-serif', category: 'Modern' },
    { id: 'varelaround', name: 'Varela Round', family: '"Varela Round", sans-serif', category: 'Modern' },
    { id: 'signika', name: 'Signika', family: '"Signika", sans-serif', category: 'Modern' },
    { id: 'catamaran', name: 'Catamaran', family: '"Catamaran", sans-serif', category: 'Modern' },
    { id: 'questrial', name: 'Questrial', family: '"Questrial", sans-serif', category: 'Modern' },
    { id: 'mavenpro', name: 'Maven Pro', family: '"Maven Pro", sans-serif', category: 'Modern' },
    { id: 'asap', name: 'Asap', family: '"Asap", sans-serif', category: 'Modern' },
    { id: 'archivo', name: 'Archivo', family: '"Archivo", sans-serif', category: 'Modern' },
    { id: 'cuprum', name: 'Cuprum', family: '"Cuprum", sans-serif', category: 'Modern' },
    { id: 'francoisone', name: 'Francois One', family: '"Francois One", sans-serif', category: 'Modern' },

    // --- TECH / MONO (26) ---
    { id: 'jetbrains', name: 'JetBrains', family: '"JetBrains Mono", monospace', category: 'Tech' },
    { id: 'orbitron', name: 'Orbitron', family: '"Orbitron", sans-serif', category: 'Tech' },
    { id: 'roboto-mono', name: 'Roboto Mono', family: '"Roboto Mono", monospace', category: 'Tech' },
    { id: 'space-mono', name: 'Space Mono', family: '"Space Mono", monospace', category: 'Tech' },
    { id: 'audiowide', name: 'Audiowide', family: '"Audiowide", cursive', category: 'Tech' },
    { id: 'press-start', name: '8-Bit', family: '"Press Start 2P", system-ui', category: 'Tech' },
    { id: 'inconsolata', name: 'Inconsolata', family: '"Inconsolata", monospace', category: 'Tech' },
    { id: 'sourcecode', name: 'Source Code', family: '"Source Code Pro", monospace', category: 'Tech' },
    { id: 'firacode', name: 'Fira Code', family: '"Fira Code", monospace', category: 'Tech' },
    { id: 'anonymous', name: 'Anonymous Pro', family: '"Anonymous Pro", monospace', category: 'Tech' },
    { id: 'vt323', name: 'VT323', family: '"VT323", monospace', category: 'Tech' },
    { id: 'sharetech', name: 'Share Tech', family: '"Share Tech Mono", monospace', category: 'Tech' },
    { id: 'cousine', name: 'Cousine', family: '"Cousine", monospace', category: 'Tech' },
    { id: 'novamono', name: 'Nova Mono', family: '"Nova Mono", monospace', category: 'Tech' },
    { id: 'synemono', name: 'Syne Mono', family: '"Syne Mono", monospace', category: 'Tech' },
    { id: 'overpassmono', name: 'Overpass Mono', family: '"Overpass Mono", monospace', category: 'Tech' },
    { id: 'teko', name: 'Teko', family: '"Teko", sans-serif', category: 'Tech' },
    { id: 'russoone', name: 'Russo One', family: '"Russo One", sans-serif', category: 'Tech' },
    { id: 'quantico', name: 'Quantico', family: '"Quantico", sans-serif', category: 'Tech' },
    { id: 'electrolize', name: 'Electrolize', family: '"Electrolize", sans-serif', category: 'Tech' },
    { id: 'saira', name: 'Saira', family: '"Saira", sans-serif', category: 'Tech' },
    { id: 'wallpoet', name: 'Wallpoet', family: '"Wallpoet", cursive', category: 'Tech' },
    { id: 'blackops', name: 'Black Ops One', family: '"Black Ops One", cursive', category: 'Tech' },
    { id: 'michroma', name: 'Michroma', family: '"Michroma", sans-serif', category: 'Tech' },
    { id: 'jura', name: 'Jura', family: '"Jura", sans-serif', category: 'Tech' },
    { id: 'syncopate', name: 'Syncopate', family: '"Syncopate", sans-serif', category: 'Tech' },

    // --- SERIF (20) ---
    { id: 'playfair', name: 'Playfair', family: '"Playfair Display", serif', category: 'Serif' },
    { id: 'lora', name: 'Lora', family: '"Lora", serif', category: 'Serif' },
    { id: 'merriweather', name: 'Merriweather', family: '"Merriweather", serif', category: 'Serif' },
    { id: 'cinzel', name: 'Cinzel', family: '"Cinzel", serif', category: 'Serif' },
    { id: 'roboto-slab', name: 'Roboto Slab', family: '"Roboto Slab", serif', category: 'Serif' },
    { id: 'ptserif', name: 'PT Serif', family: '"PT Serif", serif', category: 'Serif' },
    { id: 'notoserif', name: 'Noto Serif', family: '"Noto Serif", serif', category: 'Serif' },
    { id: 'arvo', name: 'Arvo', family: '"Arvo", serif', category: 'Serif' },
    { id: 'ebgaramond', name: 'EB Garamond', family: '"EB Garamond", serif', category: 'Serif' },
    { id: 'librebaskerville', name: 'Libre Baskerville', family: '"Libre Baskerville", serif', category: 'Serif' },
    { id: 'crimsontext', name: 'Crimson Text', family: '"Crimson Text", serif', category: 'Serif' },
    { id: 'spectral', name: 'Spectral', family: '"Spectral", serif', category: 'Serif' },
    { id: 'bitter', name: 'Bitter', family: '"Bitter", serif', category: 'Serif' },
    { id: 'domine', name: 'Domine', family: '"Domine", serif', category: 'Serif' },
    { id: 'cardo', name: 'Cardo', family: '"Cardo", serif', category: 'Serif' },
    { id: 'tinos', name: 'Tinos', family: '"Tinos", serif', category: 'Serif' },
    { id: 'vollkorn', name: 'Vollkorn', family: '"Vollkorn", serif', category: 'Serif' },
    { id: 'cormorant', name: 'Cormorant', family: '"Cormorant Garamond", serif', category: 'Serif' },
    { id: 'oldstandard', name: 'Old Standard', family: '"Old Standard TT", serif', category: 'Serif' },
    { id: 'prata', name: 'Prata', family: '"Prata", serif', category: 'Serif' },

    // --- DISPLAY / RETRO (21) ---
    { id: 'oswald', name: 'Oswald', family: '"Oswald", sans-serif', category: 'Display' },
    { id: 'righteous', name: 'Righteous', family: '"Righteous", cursive', category: 'Display' },
    { id: 'bungee', name: 'Bungee', family: '"Bungee", cursive', category: 'Display' },
    { id: 'creepster', name: 'Creepster', family: '"Creepster", cursive', category: 'Display' },
    { id: 'lobster', name: 'Lobster', family: '"Lobster", cursive', category: 'Display' },
    { id: 'abrilfatface', name: 'Abril Fatface', family: '"Abril Fatface", cursive', category: 'Display' },
    { id: 'fredoka', name: 'Fredoka', family: '"Fredoka", sans-serif', category: 'Display' },
    { id: 'alfaslab', name: 'Alfa Slab One', family: '"Alfa Slab One", cursive', category: 'Display' },
    { id: 'bangers', name: 'Bangers', family: '"Bangers", cursive', category: 'Display' },
    { id: 'monoton', name: 'Monoton', family: '"Monoton", cursive', category: 'Display' },
    { id: 'specialelite', name: 'Special Elite', family: '"Special Elite", cursive', category: 'Display' },
    { id: 'fugazone', name: 'Fugaz One', family: '"Fugaz One", cursive', category: 'Display' },
    { id: 'luckiestguy', name: 'Luckiest Guy', family: '"Luckiest Guy", cursive', category: 'Display' },
    { id: 'carterone', name: 'Carter One', family: '"Carter One", cursive', category: 'Display' },
    { id: 'gruppo', name: 'Gruppo', family: '"Gruppo", cursive', category: 'Display' },
    { id: 'unicaone', name: 'Unica One', family: '"Unica One", cursive', category: 'Display' },
    { id: 'rye', name: 'Rye', family: '"Rye", cursive', category: 'Display' },
    { id: 'sancreek', name: 'Sancreek', family: '"Sancreek", cursive', category: 'Display' },
    { id: 'graduate', name: 'Graduate', family: '"Graduate", cursive', category: 'Display' },
    { id: 'fasterone', name: 'Faster One', family: '"Faster One", cursive', category: 'Display' },
    { id: 'knewave', name: 'Knewave', family: '"Knewave", cursive', category: 'Display' },

    // --- HANDWRITING (15) ---
    { id: 'dancing', name: 'Dancing', family: '"Dancing Script", cursive', category: 'Handwriting' },
    { id: 'pacific', name: 'Pacifico', family: '"Pacifico", cursive', category: 'Handwriting' },
    { id: 'caveat', name: 'Caveat', family: '"Caveat", cursive', category: 'Handwriting' },
    { id: 'indieflower', name: 'Indie Flower', family: '"Indie Flower", cursive', category: 'Handwriting' },
    { id: 'shadows', name: 'Shadows', family: '"Shadows Into Light", cursive', category: 'Handwriting' },
    { id: 'amatic', name: 'Amatic SC', family: '"Amatic SC", cursive', category: 'Handwriting' },
    { id: 'permanent', name: 'Perm. Marker', family: '"Permanent Marker", cursive', category: 'Handwriting' },
    { id: 'patrick', name: 'Patrick Hand', family: '"Patrick Hand", cursive', category: 'Handwriting' },
    { id: 'cookie', name: 'Cookie', family: '"Cookie", cursive', category: 'Handwriting' },
    { id: 'greatvibes', name: 'Great Vibes', family: '"Great Vibes", cursive', category: 'Handwriting' },
    { id: 'sacramento', name: 'Sacramento', family: '"Sacramento", cursive', category: 'Handwriting' },
    { id: 'satisfy', name: 'Satisfy', family: '"Satisfy", cursive', category: 'Handwriting' },
    { id: 'courgette', name: 'Courgette', family: '"Courgette", cursive', category: 'Handwriting' },
    { id: 'kaushan', name: 'Kaushan', family: '"Kaushan Script", cursive', category: 'Handwriting' },
    { id: 'marck', name: 'Marck', family: '"Marck Script", cursive', category: 'Handwriting' },

    // --- SYSTEM (1) ---
    { id: 'system', name: 'System Default', family: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif', category: 'System' }
];

export const FONT_CATEGORIES: FontCategory[] = ['Modern', 'Tech', 'Serif', 'Display', 'Handwriting', 'System'];

export const getFontsByCategory = (cat: FontCategory) => FONT_LIST.filter(f => f.category === cat);
