name: Test (Rust)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@5506251899c6b1646d02b36e7b43dd06e69e347f
        with:
          toolchain: stable

      - name: Run cargo test
        working-directory: crypto-core
        run: cargo test
